[package]
name = "firc_front"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.20.0" , features = ["lexer", "unicode"] }

[build-dependencies]
lalrpop = { version = "0.20.0", features = ["lexer", "unicode"] }
